apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        image: eshopaksabfd.azurecr.io/payment-ms:latest
        ports:
        - containerPort: 443
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
            
---
apiVersion: v1
kind: Service
metadata:
  name: payment-ms
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: payment-ms
  type: ClusterIP
