apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: payment-ms
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      containers:
      - name: payment-ms
        image: eshopaksabfd.azurecr.io/payment-ms:latest
        ports:
        - containerPort: 80
          #targetPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
